### ISSUE TITLE
Опечатка в варианте ответа. ISP. Антипаттерны и запахи.

### ISSUE THREAD

**Issue by just-begin-again** [bespoyasov/solidbook#195]
[ISP. Антипаттерны и запахи.](https://solidbook.vercel.app/isp/antipatterns)
Вариант ответа №2, окончание в слове "поддержки".

![image](https://user-images.githubusercontent.com/101597204/204032565-293fd851-5272-46f2-89b6-71e7650b3930.png)

**Comment by bespoyasov** [comment]
Спасибо! Поправил ✅
