### ISSUE TITLE
Ссылки на материал к разделу устарели.

### ISSUE THREAD

**Issue by Voyager101pw** [bespoyasov/solidbook#199]
Добрый день.
В материалах раздела две ссылки недействительны.

![image](https://user-images.githubusercontent.com/78823465/204783397-b047bc2f-5446-420a-b360-079623f78348.png)
https://github.com/bespoyasov/solidbook/blob/c32f0ddafc0dd9db16b37bd21f067b123c99c59f/pages/ocp/patterns.mdx?plain=1#L276-L277

**Comment by bespoyasov** [comment]
Спасибо!
Обновил ссылки :–)
