### ISSUE TITLE
Некорректное описание примера на странице с паттернами

### ISSUE THREAD

**Issue by sunriselink** [bespoyasov/solidbook#202]
Страница https://solidbook.vercel.app/srp/patterns

На ней есть пример неверной реализации класса `CachedRequest`

![image](https://github.com/bespoyasov/solidbook/assets/3811862/2ca01136-ad08-4e82-886d-d65dc320f281)

Указано "Этот вариант всегда ссылается на значение из кэша, даже если его нет"

На самом деле данный вариант всегда возвращает результат с сервера и никогда из кэша. При таком описании пример должен был выглядеть примерно так

```typescript
async request(url: string): Promise<any> {
  const result = await this.cached.request(url);
  return Promise.resolve(this.cache[url]);
}
```

P.S. Мне кажется у поля `cached: RequestClient` неудачное название, сбивает с толку. Это скорей просто `client: RequestClient`

**Comment by bespoyasov** [comment]
Обновил. Спасибо за внимательность!
